/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXAMPLE_H_RPCGEN
#define _EXAMPLE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ARITH_PROG 0x20000001
#define ARITH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(intpair *, CLIENT *);
extern  int * add_1_svc(intpair *, struct svc_req *);
#define SUB 2
extern  int * sub_1(intpair *, CLIENT *);
extern  int * sub_1_svc(intpair *, struct svc_req *);
extern int arith_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
extern int arith_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXAMPLE_H_RPCGEN */
